### PR TITLE
feat: new logo

### LINKED ISSUE #5: New Logo?
The current logo on the website looks very blurry on a retina display beside it's using Laravel's old logo.

I think it's about time it gets some attention too.

I can share a few concepts based on the existing logo but using Laravel's new logo and high quality as well. Let me know if it interests you!

### PR DESCRIPTION
**Pull request by atymic**
cc @irazasyed

Closes #5

### CODE REVIEW

**Comment by atymic** [comment]
Have also updated the GH org profile picture & gravatar

**Comment by irazasyed** [comment]
Awesome. Looks great now. Thanks :)

**Comment by atymic** [comment]
I've also added a branding section to the readme with links to the SVG/PNG logos :)
https://deploy-preview-6--laravel-notification-channels.netlify.com/about/#branding

**Comment by irazasyed** [comment]
Good idea 👍

**Comment by atymic** [comment]
I just realised that I didn't credit you. I've added a link to your github to the section :)
https://github.com/laravel-notification-channels/website/commit/415fc8bfe0225557607f115414cfbb0d871c6f87

**Comment by irazasyed** [comment]
haha that wasn't required, tho. But It's appreciated, Thank you :)

**Pull request merged**
